project:
  type: book

book:
  title: "**Tutorials**"
  author:   
  - "Trishang Udhwani" 
  - "Novica Nakov"
  - "HÃ¥kon Kaspersen"
  sidebar: 
    logo: "images/logos/vetinst-logo-eng.png"
    background: "#EEF8F8"
  chapters:
  - index.qmd
  - part: "General"
    chapters:
      - quarto_files/part_general/posit_infrastructure_at_VI.qmd
  - part: "Configrations"
    chapters:
      - quarto_files/part_configrations/setting_home_dir.qmd
      - quarto_files/part_configrations/connecting_r_studio_to_github.qmd
  - part: "R/RStudio tutorials"
    chapters: 
      - quarto_files/part_r_rstudio_tutorials/anatomy_of_a_r_package.qmd
      - quarto_files/part_r_rstudio_tutorials/projects_in_r_studio.qmd
      - quarto_files/part_r_rstudio_tutorials/parallelization_on_workbench.qmd
      - quarto_files/part_r_rstudio_tutorials/getting_help_with_r.qmd
      - quarto_files/part_r_rstudio_tutorials/r_studio_tips_and_tricks.qmd
  - part: "Posit Connect"
    chapters: 
      - quarto_files/part_posit_connect/creating_pins_on_connect.qmd
      - quarto_files/part_posit_connect/git_backed_deployment_to_posit_connect.qmd
  - quarto_files/contributing.qmd
format:
  html:
    theme: cosmo

editor: visual
